POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit",
    "details" "An event for lovers of programmation",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/:id/attendees
Content-Type: application/json

{
    "name": "Anderson Marlon",
    "email": "anderson18.marlon@gmail.com" 
}

###

GET http://localhost:3333/events/:id

###

GET http://localhost:3333/attendees/:id/badge

###

GET http://localhost:3333/attendees/:id/check-in

###

GET http://localhost:3333/events/:id/attendees

###

GET http://localhost:3333/events/:id/attendees?query=Anderson